### ISSUE TITLE
[BUG] battlekit deleteeditedkits won't delete player kits

### ISSUE THREAD

**Issue by Tmdoofking** [toppev/strikepractice-public#21]
**Describe the bug**
/battlekit deleteeditedkits <kits>
It will delete online players kits, but offline won't (my server restart everyday, 100% sure it won't clear if server restart)
i think add per kits stuff version is better.

**To Reproduce**
/battlekit deleteeditedkits <kits>

**Versions:**
 - Server version 1.19.2

**Comment by toppev** [comment]
After executing the command it should say something like:

"Succesfully deleted 7 edited kits!" (may take some time to show)
Does that number (7 in the example) include the offline players in your case? It counts player's whose kits were modified (so not if they never edited it). SP uses offline player list to delete those kits so that wouldn't work if SP data is kept but "world" world data is not.

**Comment by Tmdoofking** [comment]
My server didn't save player data, i think that why.
I think this should be suggest now.

**Comment by toppev** [comment]
I see
This was not really well designed in the first place by me :/

I'll consider this enhancement and possibly make those better in the future.

**Comment by toppev** [comment]
not planned, closing
